### ISSUE TITLE
Розморозити. Жду

### ISSUE THREAD

**Issue by r666666** [dvoyakiy/hohlochan#6]

**Comment by dvoyakiy** [comment]
та бля мені влом, потім колись
і бек на сісярпі я єбав писати

**Comment by r666666** [comment]
та це так стас рішив порофлити)

**Comment by dvoyakiy** [comment]
> 
> 
> та це так стас рішив порофлити)

Ооо маньоври пішли понятно.
Ясно всьо з тобою! всьо ясно!! я все поняв!
